export interface MeasurementEmbeddedAppError {
  code: ErrorCodes;
  message: string;
}

export enum ErrorCodes {
  CAMERA_PERMISSION_DENIED = 'CAMERA_PERMISSION_DENIED',
  WORKER_ERROR = 'WORKER_ERROR',
  PROFILE_INFO_NOT_SET = 'PROFILE_INFO_NOT_SET',
  NO_DEVICES_FOUND = 'NO_DEVICES_FOUND',
  PAGE_NOT_VISIBLE = 'PAGE_NOT_VISIBLE',
  CAMERA_START_FAILED = 'CAMERA_START_FAILED',
  MEASUREMENT_LOW_SNR = 'MEASUREMENT_LOW_SNR',
}
